### ISSUE TITLE
fetching HTTPS feeds with CAcert certificate fail

### ISSUE THREAD

**Issue by kaifabian** [openmensa/openmensa#16]
Hi guys,

since the last update, my feeds do not get fetched anymore, since they fail with a "certificate verify failed". It seems that the updates either induced a new certificate check, or CAcert is no longer listed as a trusted CA.

Best regards,
Kai

**Comment by jgraichen** [comment]
Ah, CAcert was removed from Debian Jessie therefore it fails since we upgraded.

@mswart Manual import the CAcert root on server? Or force Kai to change certs? ;)

**Comment by kaifabian** [comment]
@jgraichen I already plan on changing the certificates (since they expire in about two weeks anyway) and the CA, but that would imply not having meal information for one of our favorite canteens for the next weeks ;P

**Comment by cmur2** [comment]
I'd vote for importing CACert anyways, might have future purposes.

**Comment by mswart** [comment]
CACert certificates are imported.
