### ISSUE TITLE
Mensa FH Erfurt is not working for Friday

### ISSUE THREAD

**Issue by jurkov** [openmensa/openmensa#18]
Dear devs at openmensa,

will testing openmensa.org i noticed there is no menu for today:
http://openmensa.org/api/v2/canteens/148/days/2015-10-30/meals
but if u open the other plan on web, there is a menu
http://www.stw-thueringen.de/deutsch/mensen/einrichtungen/erfurt/mensa-altonaer-strasse.html

Hope to see soon some food :D

best regards,
Christoph J.

**Comment by klemens** [comment]
The thueringen parser has been redone by @Anarchoschnitzel and works properly now. This can be closed.
