### ISSUE TITLE
Allow for dual opening hours and two separate meals per day

### ISSUE THREAD

**Issue by RafiKueng** [openmensa/openmensa#20]
some of our mensas have a lunch (mittagessen) and dinner (abendessen), and thus two opening hours. how should this be entered? 

    <times type="opening">
      <monday open="11:00-14:00; 17:00-20:00" />

and the meals with a category?

    <canteen>
    <day date="2012-05-29">
      <category name="Mittag - Hauptgericht">
        <meal>
          <name>Rührei mit Rahmspinat und Salzkartoffeln</name>
          <note>ovo-lacto-vegetabil</note>
          <price role="student">1.20</price>
          <price role="employee">2.60</price>
          <price role="other">3.00</price>
        </meal>
        <meal>
          <name>Hähnchengeschnetzeltes mit exotischen Früchten, dazu Bio-Reis und Mischsalat</name>
          <note>mit Geflügelfleisch</note>
          <price role="student">2.00</price>
          <price role="employee">3.35</price>
          <price role="other">4.00</price>
        </meal>
      </category>
      <category name="Mittag - Sonstiges">
        <meal>
          <name>Spargelcremsuppe</name>
          <price role="other">2.00</price>
        </meal>
      </category>
      <category name="Abend - Hauptgericht">
        <meal>
          <name>Spaghetti</name>
          <price role="other">2.00</price>
        </meal>
      </category>
    </day>

    <day date="2012-05-28">
      <closed/>
    </day>
    </canteen>

**Comment by mswart** [comment]
We had the issues for Braunschweig. The final solution was to express launch and diner as separate canteens (https://openmensa.org/c/153 and https://openmensa.org/c/154).

It is a workaround, but it is currently the best approach. Add support for multiple opening times, is not that difficult. The main issue is to support an additional indirection for the meals / categories. This has to be changed in the feed specification and the API. Break or at least extend the API to support the new indirection, requires all clients to be extended (at least if then interact with such canteens). This can only be changed on the long-term. In addition some current features like mark a canteen as favorite, should than also work on the indirection, as someone maybe only uses the lunch canteen, and want to skip the diner canteen.

Our current approach is therefor to build multiple canteens. This works with all clients and also favorite and other features that work on canteens can easily apply on both, on of them or none of them, depending what the user want.

My current idea is the support relation between canteens, to express e.g. that the two canteens are `lunch` and `diner`; this can slowly implemented in the clients, but it is not a required information. Also it will probably not implemented soon.

**Comment by RafiKueng** [comment]
That's actually not a too bad solution. It's easier to consider them as separate mensas, because in our case, they also have different days when closed ect.. (no dinner in semester break and on special days..)

So I agree and close. Thanks!
