### ISSUE TITLE
Feeds from my parser are not fetched daily.

### ISSUE THREAD

**Issue by cvzi** [openmensa/openmensa#21]
I wrote a parser for some canteens from the Heidelberg Studierendenwerk and so far everything seemed to be working fine.
But today I noticed that neither the "today" nor the "full" feed are fetched on a daily basis.

An example:
http://openmensa.org/c/277/
It says there:
> Feed "today"
> Letzte Abruf: vor 10 Stunden
> Nächster Abruf: -
> Feed "full"
> Letzte Veränderung: 04.05.2016
> Letzte Abruf: 05.05.2016
> Nächster Abruf: -

(I manually updated the "today" feed 10 hours ago)
So why is there no date for "Nächster Abruf"? Is there a setting for automatic fetching that I missed?

**Comment by mswart** [comment]
First of all, many thanks for your parser and to report the issue :+1: 

The `schedule` value was not specified for your canteens. Please take a look at [the documentation of this feed attribute](http://doc.openmensa.org/feed/v2/#optional-schedule-element). To test the scheduling I have manual set the values to `'0 8 * * *'` (8 o'clock each morning). But you must specific the value in the meta feed, as is automatically sync with it (and will probably override the values this night) - an edit form on the website itself is therefore not show. If I find time, I will add a page the view the information ...

The documentation about the current canteen, parser, source, feed system is not complete, but I hope that short description helps you to specific the needed field info. If not, report your question, reopen this issue or contact me as @mswart at `irc://freenode.net/#openmensa` directly; whatever you like.

Please note: the backend implementation is a little bit fragile/not tested by many users, so you might find new errors or unexpected behavior. As even non-intuitive interfaces are an error, I am interested in every issue.
