### ISSUE TITLE
OpenMensa (prod) stopped updating feeds

### ISSUE THREAD

**Issue by kaifabian** [openmensa/openmensa#23]
Many parsers weren't fetched fetched today, and it looks like some haven't been fetched for a while.

@mswart Could you take a look at the openmensa cron?

**Comment by kaifabian** [comment]
Btw. fetching the feeds manually works perfectly. It's just the automated feed updates that don't work.

**Comment by mswart** [comment]
Known bug due to wrongly handled feed meta data. Manual fixed for now.

**Comment by azrdev** [comment]
All darmstadt feeds are failing, currently. https://openmensa.org/parsers/12

**Comment by kaifabian** [comment]
@mswart has this been fixed now or should this stay open?
