### ISSUE TITLE
Mensa Gebäude X Universität Bielefeld is not working anymore

### ISSUE THREAD

**Issue by bodems** [openmensa/openmensa#26]
The Website of Studierendenwerk Bielefeld has changed, so openmensa isn't working anymore and just displays anything as empty: http://www.studierendenwerk-bielefeld.de

**Comment by jgraichen** [comment]
Please report this directly at the [canteen page](https://openmensa.org/c/203). OpenMensa itself does not parse any webpage. We only fetch data from parsers contributed and hosted by the community.

You can report issues like missing or wrong data directly on the canteen page. It will be forwarded to the author hosting the parser.
