### ISSUE TITLE
Canteen suggestion page is not moderated

### ISSUE THREAD

**Issue by kaifabian** [openmensa/openmensa#27]
The page on <https://openmensa.org/c/new> is not moderated. This allows users to post arbitrary content on the page. It seems that this is happening right now (there are some suspicious entries, might be that someone uses that page as a dead drop).

I suggest adding a moderation feature for that page.

**Comment by kaifabian** [comment]
@jgraichen is addressing this in #28

**Comment by jgraichen** [comment]
I am inclined to remove the wishlist from openmensa.org and have it link to here or the parser repo, simply to have fewer features to maintain. What do you think?

**Comment by cmur2** [comment]
> I am inclined to remove the wishlist from openmensa.org and have it link to here or the parser repo, simply to have fewer features to maintain. What do you think?

I'm also in favor with replacing the wishlist functionality with a link to Github issues and/or our info@ email address.
