### ISSUE TITLE
Price roles required in XML schema, but documentation says otherwise

### ISSUE THREAD

**Issue by Y0hy0h** [openmensa/openmensa#32]
The `price`'s `role` attribute is required in the XML schema. However, the [documentation](http://doc.openmensa.org/feed/v2/#price) suggests that the roles are optional. Optional prices make sense e. g. for the Aachener Academica, where some meals are subsidized, but others are the same price for everyone.

It is a minimal change that is backwards compatible.

**Comment by mswart** [comment]
You could simply use `other` as role? `other` is meant as fallback if a more specific price is not given.
The used roles must not match for different meals. Simply use the set of roles that are needed.

Rereading the documentation I do not find a hint that the role is optional. Could you please cite the exact passage. The documentation does not explain the *fallback* to the `other` role if the more specific roles are not given. I will fix this.

**Comment by Y0hy0h** [comment]
Yes, I misread it. (I kind of had a feeling that I was missing something. That's why I wrote the documentatoin "suggests"... :D) Maybe you can add something like the sentence:
> The default role is `others`. Choose it when no other role applies.

Still, is there a specific reason for requiring roles? I feel like it makes sense to omit roles in certain cases. I can't think of any issue with that.
