### ISSUE TITLE
Aasee Münster parser stopped working

### ISSUE THREAD

**Issue by PaulsBecks** [openmensa/openmensa#356]
Hey everyone, 

I recently realized the parser for the Aasee canteen in Münster stopped working.

I got in touch with the canteen and they said, they indeed stopped to provide the XML. But they provide an HTML you could use to parse the meals. They send me this link: https://muenster.my-mensa.de/essen.php?v=5326049&hyp=1&lang=de&mensa=aasee#aasee_tag_2020231

So far I didn't implement a parser for openmensa, but if none of you is working on it, I would give it a try.

Cheers.

**Comment by jgraichen** [comment]
Hi,

parsers are provided by the community. The one you are looking can be found here: https://github.com/chk1/stw2openmensa

The core project here only maintains the core application and servers. Unfortunately we do not have enough free time to maintain all parsers, but I am sure the original author would really like to get some help.

Hope that helps.
