### ISSUE TITLE
Server currently under maintainance (until later this day)

### ISSUE THREAD

**Issue by Anarchoschnitzel** [openmensa/openmensa#36]

**Comment by Anarchoschnitzel** [comment]
I am working on an App that uses the OpenMensa REST API. 
When I wanted to continue my work today, I noticed that the openmensa.org Server doesn't seem to respond. Neither the webpage nor the REST API is accessible.

**Comment by mswart** [comment]
The hardware is currently shutdown for hardware upgrades/improvements. I am sorry there was/is nor further information, but I know hardly more than you. The upgrade itself mostly over (the first server are online), I assume the service will be resume in the next hour / at least this afternoon.

I will keep the issue open until the upgrade is finished.

**Comment by mswart** [comment]
Server is back online and all services should be provided as usual.
