### ISSUE TITLE
Updated Parsers for Studentenwerk Thüringen

### ISSUE THREAD

**Issue by Anarchoschnitzel** [openmensa/openmensa#37]
Hi there!

During the last days a pull request at https://github.com/mswart/openmensa-parsers got merged, which added parsers for almost every canteen from Studentenwerk Thüringen.
I will try to document for which canteens a parser already exists but isn't working, and which parsers are completely new. 

|Canteen Name|City|current status(old parser)|new parser-link|
|---|---|---|---|
|Mensa am Wartenberg|Eisenach|-|http://omfeeds.devtation.de/thueringen/ei-wartenberg/full.xml|
|Mensa Nordhäuser str.|Erfurt|not working|http://omfeeds.devtation.de/thueringen/ef-nordhaeuser/full.xml|
|Mensa Altonaer str.|Erfurt|not-working|http://omfeeds.devtation.de/thueringen/ef-altonaer/full.xml|
|Cafeteria Schlüterstr.|Erfurt|-|http://omfeeds.devtation.de/thueringen/ef-schlueterstr/full.xml|
|Cafeteria Leipzigers.|Erfurt|-|http://omfeeds.devtation.de/thueringen/ef-leipzigerstr/full.xml|
|Mensa Weg der Freundschaft|Gera|-|http://omfeeds.devtation.de/thueringen/ge-freundschaft/full.xml|
|Mensa Ehrenberg|Ilmenau|not working|http://omfeeds.devtation.de/thueringen/il-ehrenberg/full.xml|
|Cafeteria Ehrenberg|Ilmenau|not-working|http://omfeeds.devtation.de/thueringen/il-cafeteria/full.xml|
|Nanoteria|Ilmenau|not-working|http://omfeeds.devtation.de/thueringen/il-nanoteria/full.xml|
|Roentgen Mensa|Ilmenau|-|http://omfeeds.devtation.de/thueringen/il-roentgen/full.xml|
|Mensa Carl-Zeiss Promenade|Jena|not working|http://omfeeds.devtation.de/thueringen/je-zeiss/full.xml|
|Cafeteria EAH|Jena|-|http://omfeeds.devtation.de/thueringen/je-eah/full.xml|
|Mensa Ernst Abbe Platz|Jena|not working|http://omfeeds.devtation.de/thueringen/je-ernstabbe/full.xml|
|vegeTable|Jena|-|http://omfeeds.devtation.de/thueringen/je-vegeTable/full.xml|
|Cafeteria zur Rosen|Jena|-|http://omfeeds.devtation.de/thueringen/je-rosen/full.xml|
|Mensa Philosophenweg|Jena|not working|http://omfeeds.devtation.de/thueringen/je-philosophen/full.xml|
|Cafeteria Uni Hauptgelände|Jena|-|http://omfeeds.devtation.de/thueringen/je-haupt/full.xml|
|Cafeteria Bibliothek|Jena|-|http://omfeeds.devtation.de/thueringen/je-bib/full.xml|
|Mensa Weinberghof|Nordhausen|-|http://omfeeds.devtation.de/thueringen/nh-mensa/full.xml|
|Mensa Blechhammer|Schmalkalden|-|http://omfeeds.devtation.de/thueringen/sk-mensa/full.xml|
|Cafeteria am Horn|Weimar|-|http://omfeeds.devtation.de/thueringen/we-horn/full.xml|
|Mensa am Park|Weimar|not working|http://omfeeds.devtation.de/thueringen/we-park/full.xml|
|Cafeteria Anna Amalia Bibliothek|Weimar|-|http://omfeeds.devtation.de/thueringen/we-anna/full.xml|
|Cafeteria Coudraystr.|Weimar|-|http://omfeeds.devtation.de/thueringen/we-coudray/full.xml|

It would be great if the new canteens could be added to openmensa and the ones that aren't working at the moment could be changed to use the new parsers :)

Cheers

**Comment by klemens** [comment]
@jgraichen @mswart Any news on this front? There are also two other parsers that need updating on openmensa.org, for which I don't have access (I currently can only access the Leipzig and Düsseldorf parsers): https://github.com/mswart/openmensa-parsers/pull/85, https://github.com/mswart/openmensa-parsers/pull/82

I sent Malte an email in august, but haven't heard anything back yet.

**Comment by jgraichen** [comment]
@klemens I just now made you an administrator on openmensa.org which means you can access all parsers now. Unfortunately there isn't much administration frontend otherwise. 

I'll see if I can divert some more free time on how we can improve managing parsers and canteens by the community. For now, if there is anyone else you would like to have admin permissions please drop me a note. Maybe we can move more resources and collaborators into @openmensa too...

**Comment by klemens** [comment]
@jgraichen: Thanks! I am now hosting the parsers at https://omfeeds.crpt.de and have already changed hannover, dresden, marburg to use the new server. Let's see if everyhing works smoothly tomorrow. If it does, I will switch over the other parsers.

> Maybe we can move more resources and collaborators into @openmensa too...

I also think that this is probably the best solution.

**Comment by klemens** [comment]
This (fix the thueringen parser) is done now, see https://github.com/mswart/openmensa-parsers/pull/79#issuecomment-461219207 and https://github.com/mswart/openmensa-parsers/pull/79#issuecomment-462056947
