### ISSUE TITLE
Website down? Project dead?

### ISSUE THREAD

**Issue by y0sh1DE** [openmensa/openmensa#603]

**Comment by cmur2** [comment]
Website down for me as well, project not dead ^^

**Comment by jgraichen** [comment]
I am trying to maintain the application whenever I have time, as well as running the server, applying updates etc.

The database did grow quite a bit in recent times, and the application probably needs to be moved to a bigger server, but there wasn't any time yet.

The project started as student's project during university, but everyone already graduated and is working now, which severely limits time. Unfortunately, no one else joined until then, e.g. to add some new features. Beside the core, there were many more canteens added, as well as parsers and apps developed.

**Comment by jgraichen** [comment]
The application is back up and running for now. I'll see to move it to a new server soon.
