### ISSUE TITLE
Connection to doc.openmensa.org not possible due to invalid certificate

### ISSUE THREAD

**Issue by niklas-uhl** [openmensa/openmensa#621]
The domain `doc.openmensa.org` is not reachable, because the current certificate is only valid for `htz22.openmensa.org` and `openmensa.org`.

**Comment by jgraichen** [comment]
Thanks for reporting! The main server did move yesterday, and `doc.openmensa.org` shouldn't have. I've fixed the DNS records. They will be propagated within the next hours.
