### ISSUE TITLE
Anmelden no longer works

### ISSUE THREAD

**Issue by domoritz** [openmensa/openmensa#92]
<img width="998" alt="Screen Shot 2019-05-16 at 06 30 57" src="https://user-images.githubusercontent.com/589034/57857630-638c6d00-77a4-11e9-9262-da602a4f1d59.png">

Not sure whether it's just me but I don't see a way to log in anymore.

**Comment by kaifabian** [comment]
Sorry, can't reproduce. Can you tell us which browser you used and whether the buttons appear in the source code?

**Comment by domoritz** [comment]
Ah, it's my adblocker.
